//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1TJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFactura
    {
        public int id { get; set; }
        public Nullable<int> codigoFactura { get; set; }
        public Nullable<int> codigoInventario { get; set; }
        public Nullable<decimal> precio { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Inventario Inventario { get; set; }
    }
}
