//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1TJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleInOut
    {
        public int id { get; set; }
        public Nullable<int> coidgoInOut { get; set; }
        public Nullable<int> codigoProducto { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual Inventario Inventario { get; set; }
        public virtual DetalleInOutP DetalleInOutP { get; set; }
    }
}
