//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1TJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleInOutP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleInOutP()
        {
            this.DetalleInOut = new HashSet<DetalleInOut>();
        }
    
        public int id { get; set; }
        public Nullable<int> coidgoInOut { get; set; }
        public Nullable<int> codigoProducto { get; set; }
        public Nullable<int> cantidadP { get; set; }
        public Nullable<bool> inoutType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleInOut> DetalleInOut { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual InOut InOut { get; set; }
    }
}
