//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1TJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.DetalleFactura = new HashSet<DetalleFactura>();
        }
    
        public int id { get; set; }
        public string numeroSerie { get; set; }
        public string numeroFactura { get; set; }
        public string nitFactura { get; set; }
        public string nombreFactura { get; set; }
        public string direccionFacutra { get; set; }
        public Nullable<System.DateTime> fechaFactura { get; set; }
        public Nullable<int> estadoFactura { get; set; }
        public Nullable<decimal> totalFactura { get; set; }
        public Nullable<int> cliente { get; set; }
        public Nullable<int> vendedor { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFactura> DetalleFactura { get; set; }
        public virtual estadoFacturas estadoFacturas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
