//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1TJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InOut
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InOut()
        {
            this.DetalleInOutP = new HashSet<DetalleInOutP>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fechaInOut { get; set; }
        public Nullable<int> tipoInOut { get; set; }
        public Nullable<int> cantidadInOut { get; set; }
        public Nullable<int> ubicacionInOut { get; set; }
    
        public virtual DataBodega DataBodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleInOutP> DetalleInOutP { get; set; }
        public virtual tipoInOut tipoInOut1 { get; set; }
    }
}
