//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1TJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventario()
        {
            this.DetalleFactura = new HashSet<DetalleFactura>();
            this.DetalleInOut = new HashSet<DetalleInOut>();
        }
    
        public int id { get; set; }
        public Nullable<int> codigoProducto { get; set; }
        public Nullable<int> estadoProducto { get; set; }
        public Nullable<int> ubicacionProducto { get; set; }
        public Nullable<decimal> precioVenta { get; set; }
    
        public virtual DataBodega DataBodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFactura> DetalleFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleInOut> DetalleInOut { get; set; }
        public virtual estadoProductos estadoProductos { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
